auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: 大梦几千秋丶今兮是何年
feed: /atom.xml
author_info: <a href="http://duanzhilei.tk">大梦几千秋丶今兮是何年</a>
author_info: <a href="http://duanzhilei.cc">大梦几千秋丶今兮是何年</a>
author_info: <a href="http://d-zl.xyz">大梦几千秋丶今兮是何年</a>
